let raizQuadrada1 = Math.sqrt(27)
console.log(raizQuadrada1)
let raizQuadrada2 = Math.sqrt(64)
console.log(raizQuadrada2)
let raizQuadrada3 = Math.sqrt(46)
console.log(raizQuadrada3)
let raizQuadrada4 = Math.sqrt(74)
console.log(raizQuadrada4)
let raizQuadrada5 = Math.sqrt(236)
console.log(raizQuadrada5)
let raizQuadrada6 = Math.sqrt(1892)
console.log(raizQuadrada6)

let potencia1 = Math.pow(2,7)
console.log(potencia1)
let potencia2 = Math.pow(7,7)
console.log(potencia2)
let potencia3 = Math.pow(4,9)
console.log(potencia3)
let potencia4 = Math.pow(5,5)
console.log(potencia4)
let potencia5 = Math.pow(24,7)
console.log(potencia5)
let potencia6 = Math.pow(823,21)
console.log(potencia6)